### ISSUE TITLE
Problem new version 

### ISSUE THREAD

**Issue by Thuong1234** [zecure/shadowd_php#41] opened 2021-06-14 02:43 UTC
i try to install new version but it has some error code. How i fix it? pleases!
![Screenshot (648)](https://user-images.githubusercontent.com/41165321/121832755-0487e200-ccf5-11eb-8a31-90e407214c4d.png)

**Comment by zit-hb** [comment] 2021-06-14 10:11
Do you see an error page when the connector throws the error? That was the mayor change in this new release. It contains more information on what the problem is.

In this screenshot I can only see that a FailedConnectionException is thrown, so it can't establish a connection with the shadowd server. Wrong values in the config?

**Comment by zit-hb** [comment] 2021-08-25 20:53
There hasn't been any activity in over 2 months, so I am going ahead and close the issue.

**Closed as completed by zit-hb** 2021-08-25 20:53 UTC
